---
- name: "Wordpress Installation"
  hosts: all
  become: true
  vars_files:
    - variables.yml
  tasks:

    - name: "Lamp-Installing Apache Webserver"
      yum:
        name: "{{packages}}"
        state: present
      tags:
        - lamp
    - name: "Lamp-Installing php packages"
      shell: amazon-linux-extras install php7.4 -y
      tags:
        - lamp
    - name: "Lamp-Creating httpd.conf from template"
      template:
        src: httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      tags:
        - lamp
    - name: "Lamp-Creating Virtualhost configuration file {{ httpd_domain }}"
      template:
        src: virtualhost.conf.tmpl
        dest: /etc/httpd/conf.d/default.conf
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      tags:
        - lamp
    - name: "Lamp-Creating Documentroot for the virtualhost {{httpd_domain}}"
      file:
        path: "/var/www/html/{{httpd_domain}}"
        state: directory
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      tags:
        - lamp

    - name: "Lamp-copying test pages into document root /var/www/html/{{ httpd_domain }}"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ httpd_domain }}"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      with_items:
        - test.php
        - test.html
      tags:
        - lamp
    - name: "Lamp-Running shell module to do syntax check of conf file"
      ignore_errors: true
      shell: httpd -t
      register: confsyntax_status
      tags:
        - lamp

    - name: "Content of variable confsyntax_status"
      debug:
        var: confsyntax_status
      tags:
        - lamp
    - name: "Lamp-Restarting Apache & php service"
      when: confsyntax_status.rc == 0
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - "httpd"
        - "php-fpm"
      tags:
        - lamp
          
    - name: "Lamp-mariadb-server -package Installation"
      yum:
        name: "{{ mysql_packages }}"
        state: present
      tags:
        - lamp
        - mariadb

    - name: "Lamp-Service Restarting/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
      tags:
        - lamp
        - mariadb
